baseurl = "http://smsalaken.github.io"
title = "Salaken Syed"
languageCode = "en-us"
disqusShortname = "smsalaken" #"your_disqus_shortname" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hugo-geo"
paginate = 10
publishDir = "/Users/salaken/Documents/personal/smsalaken.github.io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[author]
    name = "Salaken Syed"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
	description = 'Apparently random analysis and code snippets.'
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Random things on data science and machine learning by Salekin Mushfik"
    defaultKeywords = "Salaken, Data Scientist in Melbourne,Machine learning, Data Engineer in Melbourne, Australia"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "monokai"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Thoughts, Analysis and Code Snippets."

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    #googleAnalytics = "Your Google Analytics tracking code"
    #gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    github = "http://github.com/smsalaken"
    #bitbucket = ""
    #stackOverflow = ""
    linkedin = "http://linkedin.com/in/salaken"
    #googleplus = ""
    #facebook = ""
    twitter = ""
    #youtube = ""

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
    #flattr = ""  # populate with your flattr uid
